project_id = "sdjfutgztdkzyfvdzstv"

[functions.admin-create-user]
verify_jwt = true

[functions.admin-user-action]
verify_jwt = true

[functions.admin-list-users]
verify_jwt = true

[functions.bootstrap-admin]
verify_jwt = false

[functions.gemini-analyze]
verify_jwt = false