/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSugestaoIaRouteImport } from './routes/_authenticated/sugestao-ia'
import { Route as AuthenticatedSaidaRouteImport } from './routes/_authenticated/saida'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedEntradaRouteImport } from './routes/_authenticated/entrada'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSugestaoIaRoute = AuthenticatedSugestaoIaRouteImport.update({
  id: '/sugestao-ia',
  path: '/sugestao-ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaidaRoute = AuthenticatedSaidaRouteImport.update({
  id: '/saida',
  path: '/saida',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntradaRoute = AuthenticatedEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/setup-admin': typeof SetupAdminRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/entrada': typeof AuthenticatedEntradaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/saida': typeof AuthenticatedSaidaRoute
  '/sugestao-ia': typeof AuthenticatedSugestaoIaRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/setup-admin': typeof SetupAdminRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/entrada': typeof AuthenticatedEntradaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/saida': typeof AuthenticatedSaidaRoute
  '/sugestao-ia': typeof AuthenticatedSugestaoIaRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/setup-admin': typeof SetupAdminRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/entrada': typeof AuthenticatedEntradaRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/saida': typeof AuthenticatedSaidaRoute
  '/_authenticated/sugestao-ia': typeof AuthenticatedSugestaoIaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/nova-senha'
    | '/recuperar-senha'
    | '/setup-admin'
    | '/trocar-senha'
    | '/alertas'
    | '/configuracoes'
    | '/entrada'
    | '/historico'
    | '/perfil'
    | '/relatorio'
    | '/saida'
    | '/sugestao-ia'
    | '/admin/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/nova-senha'
    | '/recuperar-senha'
    | '/setup-admin'
    | '/trocar-senha'
    | '/alertas'
    | '/configuracoes'
    | '/entrada'
    | '/historico'
    | '/perfil'
    | '/relatorio'
    | '/saida'
    | '/sugestao-ia'
    | '/'
    | '/admin/usuarios'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/nova-senha'
    | '/recuperar-senha'
    | '/setup-admin'
    | '/trocar-senha'
    | '/_authenticated/alertas'
    | '/_authenticated/configuracoes'
    | '/_authenticated/entrada'
    | '/_authenticated/historico'
    | '/_authenticated/perfil'
    | '/_authenticated/relatorio'
    | '/_authenticated/saida'
    | '/_authenticated/sugestao-ia'
    | '/_authenticated/'
    | '/_authenticated/admin/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  SetupAdminRoute: typeof SetupAdminRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sugestao-ia': {
      id: '/_authenticated/sugestao-ia'
      path: '/sugestao-ia'
      fullPath: '/sugestao-ia'
      preLoaderRoute: typeof AuthenticatedSugestaoIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saida': {
      id: '/_authenticated/saida'
      path: '/saida'
      fullPath: '/saida'
      preLoaderRoute: typeof AuthenticatedSaidaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrada': {
      id: '/_authenticated/entrada'
      path: '/entrada'
      fullPath: '/entrada'
      preLoaderRoute: typeof AuthenticatedEntradaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEntradaRoute: typeof AuthenticatedEntradaRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedSaidaRoute: typeof AuthenticatedSaidaRoute
  AuthenticatedSugestaoIaRoute: typeof AuthenticatedSugestaoIaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEntradaRoute: AuthenticatedEntradaRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedSaidaRoute: AuthenticatedSaidaRoute,
  AuthenticatedSugestaoIaRoute: AuthenticatedSugestaoIaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  SetupAdminRoute: SetupAdminRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
